import { afterAll, afterEach, beforeAll } from 'vitest'
import { setupWorker } from 'msw/browser'
import { handlers } from './handlers'

// MSW in Vitest Browser Mode: requests run in a real browser, so we intercept
// with a Service Worker (msw/browser), not the Node `setupServer`. The worker
// script lives at tests/public/mockServiceWorker.js — a TEST-ONLY publicDir
// (vitest.config.ts) so it never ships in the production bundle. Generated by
// `msw init tests/public`, committed to the repo and refreshed by `make install`.
export const worker = setupWorker(...handlers)

beforeAll(async () => {
  await worker.start({ onUnhandledRequest: 'bypass', quiet: true })
})

afterEach(() => {
  worker.resetHandlers()
})

afterAll(() => {
  worker.stop()
})
