import { afterAll, afterEach, beforeAll } from 'vitest'
import { setupWorker } from 'msw/browser'
import { handlers } from './handlers'

// MSW in Vitest Browser Mode: requests run in a real browser, so we intercept
// with a Service Worker (msw/browser), not the Node `setupServer`. The worker
// script lives at public/mockServiceWorker.js (generated by `msw init public`,
// committed to the repo and refreshed by `make install`).
export const worker = setupWorker(...handlers)

beforeAll(async () => {
  await worker.start({ onUnhandledRequest: 'bypass', quiet: true })
})

afterEach(() => {
  worker.resetHandlers()
})

afterAll(() => {
  worker.stop()
})
